# This is a basic workflow to help you get started with Actions

name: Firebase CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install firebase-tools
      run: |
        sudo npm install -g firebase-tools
        firebase use 917690507553 --token ${{ secrets.FIREBASE_TOKEN }}
    
    - name: Install dependencies & Build website
      run: |
        npm ci
        npm run build
        
    - name: Deploy to production site
      if: github.ref == 'refs/heads/main'
      run: firebase deploy --only hosting --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"

    - name: Archive build artifact
      uses: actions/upload-artifact@master
      with:
        path: dist
